name: ci

on:
  release:
    types: [created, edited]
  workflow_dispatch: # Put here!!

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ github.repository }}:latest
      - name: Run tests
        run: |
          docker run --rm -v $(pwd)/sample:/workspace ${{ github.repository }}:latest \
          --pdf-engine=xelatex --listings --fail-if-warnings \
          --filter pandoc-crossref --filter pandoc-latex-environment --filter py-pandoc-include-code \
          --lua-filter multibib.lua --lua-filter diagram.lua \
          -H example.tex --metadata-file=example.yaml example.md -s -o example.pdf
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.date.outputs.time }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
